"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 09:47:21.968967
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=48), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_ts', ['ts'], unique=False)

    op.create_table('datasets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('license', sa.String(length=80), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('detection_rules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('detector', sa.String(length=48), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('hostname', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=False),
    sa.Column('device_type', sa.String(length=24), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('zone', sa.String(length=16), nullable=False),
    sa.Column('criticality', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('open_ports', sa.JSON(), nullable=False),
    sa.Column('protocols', sa.JSON(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=False),
    sa.Column('position', sa.JSON(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('criticality BETWEEN 1 AND 5', name='ck_device_criticality'),
    sa.CheckConstraint('risk_score BETWEEN 0 AND 100', name='ck_device_risk'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_device_type'), ['device_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_hostname'), ['hostname'], unique=True)
        batch_op.create_index(batch_op.f('ix_devices_ip'), ['ip'], unique=True)

    op.create_table('mitre_techniques',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tactic', sa.String(length=48), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mitre_techniques', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mitre_techniques_tactic'), ['tactic'], unique=False)

    op.create_table('threat_indicators',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=48), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'value', name='uq_indicator')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=48), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('behavior_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('baseline', sa.JSON(), nullable=False),
    sa.Column('current', sa.JSON(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('connections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('src_device_id', sa.String(length=32), nullable=False),
    sa.Column('dst_device_id', sa.String(length=32), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('bytes_per_hour', sa.BigInteger(), nullable=False),
    sa.Column('connections_per_hour', sa.Integer(), nullable=False),
    sa.Column('suspicious', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dst_device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('src_device_id', 'dst_device_id', 'protocol', name='uq_connection_pair')
    )
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_index('ix_connection_dst', ['dst_device_id'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=False),
    sa.Column('assignee_id', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('risk_score BETWEEN 0 AND 100', name='ck_incident_risk'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)

    op.create_table('network_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=False),
    sa.Column('dst_ip', sa.String(length=45), nullable=False),
    sa.Column('src_device_id', sa.String(length=32), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('bytes_sent', sa.Integer(), nullable=False),
    sa.Column('bytes_received', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['src_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('network_events', schema=None) as batch_op:
        batch_op.create_index('ix_event_src_ts', ['src_ip', 'ts'], unique=False)
        batch_op.create_index('ix_event_ts', ['ts'], unique=False)
        batch_op.create_index('ix_event_type_ts', ['event_type', 'ts'], unique=False)

    op.create_table('replay_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('packet_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=45), nullable=False),
    sa.Column('destination', sa.String(length=45), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('detection_class', sa.String(length=12), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detector', sa.String(length=48), nullable=False),
    sa.Column('mitre_techniques', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.String(length=512), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alert_incident', ['incident_id'], unique=False)
        batch_op.create_index('ix_alert_ts', ['ts'], unique=False)

    op.create_table('investigation_notes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('author_id', sa.String(length=32), nullable=False),
    sa.Column('body', sa.String(length=4000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigation_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigation_notes_incident_id'), ['incident_id'], unique=False)

    op.create_table('response_recommendations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('rationale', sa.String(length=512), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('response_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_recommendations_incident_id'), ['incident_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('alert_id', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['network_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_alert', ['alert_id'], unique=False)

    op.create_table('incident_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('alert_id', sa.String(length=32), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('link_reason', sa.String(length=256), nullable=False),
    sa.Column('link_confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'position', name='uq_incident_position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_events')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_alert')

    op.drop_table('evidence')
    with op.batch_alter_table('response_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_recommendations_incident_id'))

    op.drop_table('response_recommendations')
    with op.batch_alter_table('investigation_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigation_notes_incident_id'))

    op.drop_table('investigation_notes')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_alert_ts')
        batch_op.drop_index('ix_alert_incident')

    op.drop_table('alerts')
    op.drop_table('replay_sessions')
    with op.batch_alter_table('network_events', schema=None) as batch_op:
        batch_op.drop_index('ix_event_type_ts')
        batch_op.drop_index('ix_event_ts')
        batch_op.drop_index('ix_event_src_ts')

    op.drop_table('network_events')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_status'))

    op.drop_table('incidents')
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_index('ix_connection_dst')

    op.drop_table('connections')
    op.drop_table('behavior_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('threat_indicators')
    with op.batch_alter_table('mitre_techniques', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mitre_techniques_tactic'))

    op.drop_table('mitre_techniques')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_ip'))
        batch_op.drop_index(batch_op.f('ix_devices_hostname'))
        batch_op.drop_index(batch_op.f('ix_devices_device_type'))

    op.drop_table('devices')
    op.drop_table('detection_rules')
    op.drop_table('datasets')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_ts')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
